config/routes.rb
Rails.application.routes.draw do

  root 'researches#index'
  devise_for :users


  get '/home/index' => 'homes#index'


  #routes for research
  get '/research/index' => 'researches#index'
  
  get '/research/new' => 'researches#new'
  post '/research/new' => 'researches#create'
  get '/research/edit' => 'research#edit'
  get '/research/:id' => 'researches#show'
  get '/research/:id/edit' => 'researches#edit'
  post '/research/:id/edit' => 'researches#update'
  get '/research/destory' => 'researches#destroy'
  get '/research/:id/destroy' => 'researches#destroy'

  #routes for officers
  get 'officer/index' => 'officers#index'
  get 'officer/new' => 'officers#new'
  post 'officer/new' => 'officers#create'
  get 'officer/edit' => 'officers#edit'
  get 'officer/:id' => 'officers#show'
  get 'officer/:id/edit' => 'officers#edit'
  post 'officer/:id/edit' => 'officers#update'

  #routes for professors
  get 'professor/index' => 'professors#index'
  get 'professor/new' => 'professors#new'
  post 'professor/new' => 'professors#create'
  get 'professor/edit' => 'professors#edit'
  get 'professor/:id' => 'professors#show'
  get 'professor/:id/edit' => 'professors#edit'
  post 'professor/:id/edit' => 'professors#update'
  get 'professor/destroy' => 'professors#destroy'
  get 'professor/:id/destroy' => 'professors#destroy'

  #routes for about
  get 'about/index' => 'abouts#index'
  get 'about/new' => 'abouts#new'
  post 'about/new' => 'abouts#create'
  get 'about/edit' => 'abouts#edit'
  get 'about/:id' => 'abouts#show'
  get 'about/:id/edit' => 'abouts#edit'
  post 'about/:id/edit' => 'abouts#update'

  #routes for event
  get 'event/eventlist' => 'events#eventlist'
  get 'event/index' => 'events#index'
  get 'event/new' => 'events#new'
  post 'event/new' => 'events#create'
  get 'event/edit' => 'events#edit'
  get 'event/:id' => 'events#show'
  get 'event/:id/edit' => 'events#edit'
  post 'event/:id/edit' => 'events#update'
  get 'event/destroy' => 'events#destroy'
  get 'event/:id/destroy' => 'events#destroy'


    #routes for subjects
    get 'subject/index' => 'subjects#index'
    get 'subject/new' => 'subjects#new'
    post 'subject/new' => 'subjects#create'
    get 'subject/edit' => 'subjects#edit'
    get 'subject/:id' => 'subjects#show'
    get 'subject/:id/edit' => 'subjects#edit'
    post 'subject/:id/edit' => 'subjects#update'
    get 'subject/destroy' => 'subjects#destroy'
    get 'subject/:id/destroy' => 'subjects#destroy'


end

app/models/event.rb
class Event < ApplicationRecord

    has_attached_file :event_img, :styles => { :event_index => "250x350>", :event_show => "325x475>" }, :default_url => "/images/:style/missing.png"
    validates_attachment_content_type :event_img, content_type: /\Aimage\/.*\z/

    belongs_to :user

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    before_action :find_event, only: [:show, :edit, :update, :destroy]

  def index
    @events = Event.all
  end

  def eventlist
    @events = Event.all
  end

  def new
    @events = current_user.events.build
  end

  def show

  end


  def create
    @event = current_user.events.build(event_params)

    if @event.save
      redirect_to event_index_path
    end

  end

  def update

    if @event.update(event_params)
      redirect_to event_index_path
    end

  end

  def destroy

    if @event.destroy
      redirect_to event_index_path
    end

  end

  private

  def event_params
    params.require(:event).permit(:event_name, :event_description, :event_date, :event_venue, :event_img)
  end

  def find_event
    @event = Event.find(params[:id])
  end

end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/edit.html.erb
<h1> Edit</h1>

<%= form_for(:event) do |f| %>

<%= f.label "Event Title" %> <br>
<%= f.text_area :event_name %><br>

<%= f.label "Description" %><br>
<%= f.text_area :event_description %><br>

<%= f.label "Date" %><br>
<%= f.date_select :event_date %><br>

<%= f.label "Venue" %><br>
<%= f.text_area :event_venue %><br>

<%= f.label "Poster" %><br>
<%= f.file_field :event_img %><br>


  <%= f.submit "Update Event" %><br>
  <%= link_to "Back", event_index_path %>
  <% end %>

app/views/events/eventlist.html.erb
<div class = "row">
	<% @events.each do |event| %>
	  <div class = "col-md-4">
 	 	<div class = "event-instance">
		 	<a class = "event-name" href="/event/<%= event.id%>"><%= event.event_name %> </a><br>
		    <span class = "event-date"> <%= event.event_date.strftime("%B %d, %Y") %> </span> <br>
		    <%= event.event_description %><br>
		    <%= event.event_venue %>
	 	</div>
	   </div>
	

	<% end %> 

</div>
	
	
	

app/views/events/index.html.erb
<div class = "see-event"> 
<a href="/event/eventlist" class = "btn btn-primary btn-lg" role = "button"> See more Events . . </a>
</div>  


<div class = "row" >

  <% @events.each do |x| %>
      <div class = "col-md-3" >
        <div class = "event-title-header" >
          <a href = "/event/<%= x.id%>" > <%= x.event_name %> </a><br>
          <span> <%= x.event_date.strftime("%B %d, %Y") %></span>
        </div>
          <a href="/event/<%= x.id%>" > <%= image_tag x.event_img.url(:event_index), class: "event_img" %> </a> <br>

      </div>
  <% end %>

</div>


<br>
<br>
<br>
<% if current_user == 1 %>
  <%= link_to "Insert Event" , event_new_path %>
<% end %>

app/views/events/new.html.erb
<h1> Form </h1>

<%= form_for (:event) do |f| %>

  <%= f.label "Event Title" %> <br>
  <%= f.text_field :event_name %><br>


  <%= f.label "Description" %><br>
  <%= f.text_area :event_description %><br>

  <%= f.label "Date" %><br>
  <%= f.date_select :event_date %><br>

  <%= f.label "Venue" %><br>
  <%= f.text_field :event_venue %><br><br>


    <%= f.label "Poster" %><br>
    <%= f.file_field :event_img %><br>


  <%= f.submit "Insert a Event" %><br><br>
  <%= link_to "Back", event_index_path %>

  <% end %>

app/views/events/show.html.erb
<div class = "row" >

</div>

  <div class = "col-md-8" >
    <h3> Event Title </h3>
    <%= @event.event_name %> <br>
    <h3> Description </h3>
    <%= @event.event_description %> <br>
    <h3> Date </h3>
    <%= @event.event_date %> <br>
    <h3> Venue </h3>
    <%= @event.event_venue %> <br>

<%= link_to "Back", event_index_path %>

    <% if @event.user == current_user %>
      <%= link_to "Edit", "/event/#{@event.id}/edit" %>
      <%= link_to "Delete" , "/event/#{@event.id}/destroy" %>
    <% end %>

  </div>

</div>