config/routes.rb
Rails.application.routes.draw do

  root 'researches#index'
  devise_for :users


  get '/home/index' => 'homes#index'


  #routes for research
  get '/research/index' => 'researches#index'
  
  get '/research/new' => 'researches#new'
  post '/research/new' => 'researches#create'
  get '/research/edit' => 'research#edit'
  get '/research/:id' => 'researches#show'
  get '/research/:id/edit' => 'researches#edit'
  post '/research/:id/edit' => 'researches#update'
  get '/research/destory' => 'researches#destroy'
  get '/research/:id/destroy' => 'researches#destroy'

  #routes for officers
  get 'officer/index' => 'officers#index'
  get 'officer/new' => 'officers#new'
  post 'officer/new' => 'officers#create'
  get 'officer/edit' => 'officers#edit'
  get 'officer/:id' => 'officers#show'
  get 'officer/:id/edit' => 'officers#edit'
  post 'officer/:id/edit' => 'officers#update'

  #routes for professors
  get 'professor/index' => 'professors#index'
  get 'professor/new' => 'professors#new'
  post 'professor/new' => 'professors#create'
  get 'professor/edit' => 'professors#edit'
  get 'professor/:id' => 'professors#show'
  get 'professor/:id/edit' => 'professors#edit'
  post 'professor/:id/edit' => 'professors#update'
  get 'professor/destroy' => 'professors#destroy'
  get 'professor/:id/destroy' => 'professors#destroy'

  #routes for about
  get 'about/index' => 'abouts#index'
  get 'about/new' => 'abouts#new'
  post 'about/new' => 'abouts#create'
  get 'about/edit' => 'abouts#edit'
  get 'about/:id' => 'abouts#show'
  get 'about/:id/edit' => 'abouts#edit'
  post 'about/:id/edit' => 'abouts#update'

  #routes for event
  get 'event/eventlist' => 'events#eventlist'
  get 'event/index' => 'events#index'
  get 'event/new' => 'events#new'
  post 'event/new' => 'events#create'
  get 'event/edit' => 'events#edit'
  get 'event/:id' => 'events#show'
  get 'event/:id/edit' => 'events#edit'
  post 'event/:id/edit' => 'events#update'
  get 'event/destroy' => 'events#destroy'
  get 'event/:id/destroy' => 'events#destroy'


    #routes for subjects
    get 'subject/index' => 'subjects#index'
    get 'subject/new' => 'subjects#new'
    post 'subject/new' => 'subjects#create'
    get 'subject/edit' => 'subjects#edit'
    get 'subject/:id' => 'subjects#show'
    get 'subject/:id/edit' => 'subjects#edit'
    post 'subject/:id/edit' => 'subjects#update'
    get 'subject/destroy' => 'subjects#destroy'
    get 'subject/:id/destroy' => 'subjects#destroy'


end

app/models/professor.rb
class Professor < ApplicationRecord
	belongs_to :user
end

app/controllers/professors_controller.rb
class ProfessorsController < ApplicationController
  before_action :find_professor, only: [ :show, :update, :destroy, :edit ]

  def index
    @professors = Professor.all
  end

  def show

  end

  def new
    @professor = current_user.professors.build


  def create
    @professor = current_user.professors.build(professor_params)
      if @professor.save
          flash[:notice] = "Successfuly Added"
          redirect_to professor_index_path
      end
  end

  end

  def update
    if @professor.update(professor_params)
       redirect_to professor_index_path
    end
  end

  def edit
  end

  def destroy
    if @professor.destroy
      flash[:notice] = "Successfuly deleted"
      redirect_to professor_index_path
    end
  end



  private

  def professor_params
    params.require(:professor).permit( :name, :position, :educ_attainment, :user_id)
  end

  def find_professor
    @professor = Professor.find(params[:id])
  end

end

app/helpers/professors_helper.rb
module ProfessorsHelper
end

app/views/professors/edit.html.erb
<h1> Edit </h1>

<%= form_for(:professor) do |f|  %>
  <%= f.label :"Name"  %> <br>
  <%= f.text_field :name %><br>

  <%= f.label :"Position" %><br>
  <%= f.text_field :position %><br>

  <%= f.label :"Educational Attainment" %><br>
  <%= f.text_area :educ_attainment %><br>

  <%= f.submit "Update Professor" %>

  <% end %>

app/views/professors/index.html.erb
<h1> Faculty Members </h1>

  <% @professors.each do |x| %>
      <a href="/professor/<%= x.id %>" > <%= x.name %></a> <br>
    <%= x.position %> <br>
    <br>
    <br>
    <br>
  <% end %>

<% if current_user == 1 %>
    <%= link_to "Add professor" , professor_new_path %>
 <% end %>
    <%= link_to "Back" , officer_index_path %>

app/views/professors/new.html.erb
<%= form_for(:professor) do |f|  %>
  <%= f.label :"Name"  %> <br>
  <%= f.text_field :name %><br>

  <%= f.label :"Position" %><br>
  <%= f.text_field :position %><br>

  <%= f.label :"Educational Attainment" %><br>
  <%= f.text_area :educ_attainment %><br>

  <%= f.submit "Add Professor" %>
  <% end %>
  <%= link_to "Back" , officer_index_path %>

app/views/professors/show.html.erb
<%= @professor.name %> <br>
<%= @professor.position %> <br>
<%= @professor.educ_attainment %> <br>
<br>
<br>

<%= link_to "Back" , professor_index_path %>

<% if @professor.user_id == current_user %>
<%= link_to "Edit" , "/professor/#{@professor.id}/edit" %>
<%= link_to "Delete" , "/professor/#{@professor.id}/destroy" %>
<% end %>