config/routes.rb
Rails.application.routes.draw do

  root 'researches#index'
  devise_for :users


  get '/home/index' => 'homes#index'


  #routes for research
  get '/research/index' => 'researches#index'
  
  get '/research/new' => 'researches#new'
  post '/research/new' => 'researches#create'
  get '/research/edit' => 'research#edit'
  get '/research/:id' => 'researches#show'
  get '/research/:id/edit' => 'researches#edit'
  post '/research/:id/edit' => 'researches#update'
  get '/research/destory' => 'researches#destroy'
  get '/research/:id/destroy' => 'researches#destroy'

  #routes for officers
  get 'officer/index' => 'officers#index'
  get 'officer/new' => 'officers#new'
  post 'officer/new' => 'officers#create'
  get 'officer/edit' => 'officers#edit'
  get 'officer/:id' => 'officers#show'
  get 'officer/:id/edit' => 'officers#edit'
  post 'officer/:id/edit' => 'officers#update'

  #routes for professors
  get 'professor/index' => 'professors#index'
  get 'professor/new' => 'professors#new'
  post 'professor/new' => 'professors#create'
  get 'professor/edit' => 'professors#edit'
  get 'professor/:id' => 'professors#show'
  get 'professor/:id/edit' => 'professors#edit'
  post 'professor/:id/edit' => 'professors#update'
  get 'professor/destroy' => 'professors#destroy'
  get 'professor/:id/destroy' => 'professors#destroy'

  #routes for about
  get 'about/index' => 'abouts#index'
  get 'about/new' => 'abouts#new'
  post 'about/new' => 'abouts#create'
  get 'about/edit' => 'abouts#edit'
  get 'about/:id' => 'abouts#show'
  get 'about/:id/edit' => 'abouts#edit'
  post 'about/:id/edit' => 'abouts#update'

  #routes for event
  get 'event/eventlist' => 'events#eventlist'
  get 'event/index' => 'events#index'
  get 'event/new' => 'events#new'
  post 'event/new' => 'events#create'
  get 'event/edit' => 'events#edit'
  get 'event/:id' => 'events#show'
  get 'event/:id/edit' => 'events#edit'
  post 'event/:id/edit' => 'events#update'
  get 'event/destroy' => 'events#destroy'
  get 'event/:id/destroy' => 'events#destroy'


    #routes for subjects
    get 'subject/index' => 'subjects#index'
    get 'subject/new' => 'subjects#new'
    post 'subject/new' => 'subjects#create'
    get 'subject/edit' => 'subjects#edit'
    get 'subject/:id' => 'subjects#show'
    get 'subject/:id/edit' => 'subjects#edit'
    post 'subject/:id/edit' => 'subjects#update'
    get 'subject/destroy' => 'subjects#destroy'
    get 'subject/:id/destroy' => 'subjects#destroy'


end

app/models/about.rb
class About < ApplicationRecord
  has_attached_file :about_img, :styles => { :about_index => "500x250>"}, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :about_img, content_type: /\Aimage\/.*\z/

  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord

    has_attached_file :event_img, :styles => { :event_index => "250x350>", :event_show => "325x475>" }, :default_url => "/images/:style/missing.png"
    validates_attachment_content_type :event_img, content_type: /\Aimage\/.*\z/

    belongs_to :user

end

app/models/home.rb
class Home < ApplicationRecord
  has_attached_file :adnu_img, :styles => { :adnu_index => "30x30>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :adnu_img, content_type: /\Aimage\/.*\z/
  
end

app/models/officer.rb
class Officer < ApplicationRecord
	belongs_to :user
end

app/models/professor.rb
class Professor < ApplicationRecord
	belongs_to :user
end

app/models/research.rb
class Research < ApplicationRecord

  has_attached_file :research_img, :styles => { :research_index => "250x350>", :research_show => "325x475>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :research_img, content_type: /\Aimage\/.*\z/


  belongs_to :user
  
end

app/models/subject.rb
class Subject < ApplicationRecord
  validates :subject_title, presence:true
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :researches
  has_many :abouts
  has_many :events
  has_many :subjects
  has_one :officer
  has_many :professors
end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController
  before_action :find_about, only: [:show, :destroy, :edit, :update]
  before_action :authenticate_user!, except: [:index , :show]


  def index
    @abouts = About.all
  end

  def new
    @about = current_user.abouts.build
  end

  def show
  end

  def create

      @about = current_user.abouts.build(about_params)

        if @about.save
          redirect_to root_path
        end
  end

  def edit

  end
  
  def update
    if @about.update(about_params)
      redirect_to about_index_path
    end

  end



  def destroy
    if @about.destroy
      redirect_to about_index_path
      flash[:notice] = "Successfuly deleted"
    end
  end
  private

  def about_params
    params.require(:about).permit(:mission, :vision, :his, :about_img)
  end

  def find_about
    @about = About.find(params[:id])
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    before_action :find_event, only: [:show, :edit, :update, :destroy]

  def index
    @events = Event.all
  end

  def eventlist
    @events = Event.all
  end

  def new
    @events = current_user.events.build
  end

  def show

  end


  def create
    @event = current_user.events.build(event_params)

    if @event.save
      redirect_to event_index_path
    end

  end

  def update

    if @event.update(event_params)
      redirect_to event_index_path
    end

  end

  def destroy

    if @event.destroy
      redirect_to event_index_path
    end

  end

  private

  def event_params
    params.require(:event).permit(:event_name, :event_description, :event_date, :event_venue, :event_img)
  end

  def find_event
    @event = Event.find(params[:id])
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/officers_helper.rb
module OfficersHelper
end

app/helpers/professors_helper.rb
module ProfessorsHelper
end

app/helpers/researches_helper.rb
module ResearchesHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Website</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>


  </head>


  <body>
    <div class = "banner">
     <%= image_tag("adnu_logo.png", size: "30x30", alt: "adnu logo") %>
     Ateneo De Naga University
      <div class = "toright">
            
            <% if !user_signed_in? %>
            <%= link_to "Sign Up", new_user_registration_path, class: "navbar-signout"  %>
            <% end %>

            <% if user_signed_in? %>
                <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "navbar-signout"  %>
                <% else %>
                <%= link_to "Log in" , new_user_session_path, class: "navbar-signout" %> 
            <% end %>
          </div>
    </div>

    <div class = "header" >
     <%= image_tag("psych_logo", size: "100x100", alt: "adnu logo") %>
        DEPARTMENT OF PSYCHOLOGY 

          <div class = "search-field" >
            <%= form_tag "/search_items/" do %>
              <input type="search_string" class="form-control" placeholder="Search for..." >
            <% end %>

                
          </div>

      
    </div>

    <nav class = "navbar navbar-default">
      <div class = "container" >
        <div class = "navbar-header" >
          <%= link_to "Home" , event_index_path, class: "navbar-brand" %>
          <%= link_to "Subjects" , subject_index_path, class: "navbar-brand" %>
          <%= link_to "Research" , research_index_path, class: "navbar-brand" %>
          <%= link_to "Events" , event_eventlist_path, class: "navbar-brand" %>
          <%= link_to "People" , officer_index_path, class: "navbar-brand" %>
          <%= link_to "About Us" , about_index_path, class: "navbar-brand" %>

       </div>
        

    </div>

    </nav>

    <p class="notice"><%= notice %></p>

    <p class="alert"><%= alert %></p>



 <div class = "container" >
 <%= yield %>
 </div>

 <div class = "footer" >
          Footer
 </div>

 </body>
  
</html>